kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31001
    hostPort: 31001
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 31002
    hostPort: 31002
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 31003
    hostPort: 31003
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 31004
    hostPort: 31004
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 31005
    hostPort: 31005
    listenAddress: "0.0.0.0"
    protocol: TCP
